### ISSUE TITLE
drop storing null and undefined values

### ISSUE THREAD

**Issue by ralphtheninja** [Level/abstract-leveldown#120]
EDIT: Poll locked.

![screenshot from 2018-07-08 12-58-34](https://user-images.githubusercontent.com/308049/42419110-ad83d38a-82ae-11e8-8cf4-259d93ad73be.png)

Also see discussion here https://github.com/Level/abstract-leveldown/pull/119

**Comment by ralphtheninja** [comment]
I'm not saying we should do this now. But we might want to consider it and release a new major version.

**Comment by vweevers** [comment]
Reasons for dropping:

- `chunk === null` signifies end in streams
- `key === undefined` signifies end in iterators
- modules like `level-sublevel` do `op.type = op.value === undefined ? 'del' : 'put'`
- modules like `level-option-wrap` do `opts.gt === undefined`
- besides all that, just common practice, `== null` signifies a missing value (a problem to be fixed)
- the end result of *not storing* a value like this is the same (you have nothing)

**Comment by vweevers** [comment]
It might be a problem for encodings like `bytewise` that encode `null` and/or `undefined`, commonly used as lower and upper bounds.

@deanlandolt what's your take on this?

**Comment by vweevers** [comment]
Unless, with bytewise, you only need null and undefined for ltgte ranges, not storage.

**Comment by vweevers** [comment]
What users of bytewise could do is wrap keys and values in arrays. E.g. `db.put([null, 123], 'foo')` and `db.createReadStream({ gt: [null] })`. Seems like a fair expectation, considering [all the pro's for dropping](https://github.com/Level/abstract-leveldown/issues/120#issuecomment-331065563) as well as the [current poll tally](https://github.com/Level/abstract-leveldown/issues/120#issue-255010740) (6:2).

**Comment by vweevers** [comment]
Following https://github.com/Level/encoding-down/issues/42, the new plan is to reject nullish keys and values, but allow nullish range options. Long-term I think this can be fixed in `abstract-leveldown` and implementations by:

- Not touching range options in `abstract#_setupIteratorOptions` (no need for #222)
- Changing `abstract#_serializeKey` to an identity function
- Rejecting nullish keys and values (before calling `_serializeKey` and `_serializeValue`)
- Passing range options through `_serializeKey` (#130)
- Adding `leveldown#_serializeKey` to convert `null` to an empty string (not strictly required, but to avoid doing `String(null)`), Buffer as-is, everything else to a string.

So by default, `abstract-leveldown` wouldn't coerce anything. The only "rule" it would impose is that keys and values can't be nullish.

**Comment by vweevers** [comment]
Note: the abstract tests currently assume that a nullish range option is ignored (i.e. the same as *not* specifying the range option). We can keep those tests. It means we expect the implementation to either *delegate* to an underlying store, *encode* nullish, *serialize* nullish, or finally, *ignore* nullish.

**Comment by ralphtheninja** [comment]
@vweevers Thanks for thinking this through. So lets still do the https://github.com/Level/encoding-down/pull/45 "hack" for now, add some tests and clean it up under the hood.

**Comment by vweevers** [comment]
![image](https://user-images.githubusercontent.com/3055345/40233070-c10e02fc-5aa1-11e8-943e-3cadfab6b6b9.png)
