### ISSUE TITLE
run tests in the browser using e.g. zuul

### ISSUE THREAD

**Issue by ralphtheninja** [Level/abstract-leveldown#123]
see https://github.com/Level/abstract-leveldown/pull/93 (similar setup to what `memdown` does)

**Comment by vweevers** [comment]
We'll need to create subaccounts in Sauce Labs for this. Currently `memdown` uses the main `level-ci` account, which is my mistake. I learned that an account is implicitly linked to a project, because you get tests, settings, access keys and badges per account. So two projects shouldn't share the same account. But they cán share the same parent account, which allows admins to manage all subaccounts.

It's a bit painful that each (sub)account has to have a unique email address. We can create additional gmails and forward them. Or perhaps it's time to have proper `@leveldb.org` addresses.

Our Sauce Labs account structure will be something like:

- level-ci
  - sub: memdown
  - sub: abstract-leveldown

@ralphtheninja ping me when you get around to this, I'll help.

**Comment by vweevers** [comment]
@ralphtheninja It turns out that you can have only 1 subaccount, and it isn't public. Not all that useful.

So we'll need separate Sauce Labs accounts for each repo. We can however reuse our gmail address, with aliases. E.g. for the memdown account we'll use `leveldb.org+memdown@`, for `abstract-leveldown` we use `leveldb.org+abstract.leveldown@`, etc.

**Comment by vweevers** [comment]
Everything else is passing. Chrome, firefox, edge, iphone and android.

**Comment by ralphtheninja** [comment]
> Everything else is passing. Chrome, firefox, edge, iphone and android.

Awesome!

**Comment by vweevers** [comment]
IE11 is passing now, but IE9 fails on `const`:

![image](https://user-images.githubusercontent.com/3055345/39961967-7101966a-5642-11e8-8e07-c841a3681d16.png)

**Comment by vweevers** [comment]
[Usage of IE9 is 0.12%](https://caniuse.com/usage-table) though. [IE9 does not have IndexedDB](https://caniuse.com/#search=indexeddb), so `level-js` is not gonna work anyway. PouchDB targets IE10+. We don't target IE9 in `memdown` anymore. The only remaining alternative for IE users, `localstorage-down`, is heavily outdated. I don't plan on supporting IE9 in my fork, `webstorage-down`.

Shall we officially drop IE9?

**Comment by vweevers** [comment]
That still leaves IE10, which also doesn't support `const`.

**Comment by ralphtheninja** [comment]
> Shall we officially drop IE9?

I wouldn't mind dropping it.

> That still leaves IE10, which also doesn't support const.

We can just drop `const`.

**Comment by vweevers** [comment]
> But maybe we have problems with const in other modules?

Probably. Another reason for adding browser tests across the board :)

**Comment by vweevers** [comment]
Found usage of `const` in `levelup` (only in tests, benchmarks and readme code though), `level-packager` and `level-ttl`.

**Comment by ralphtheninja** [comment]
> Probably. Another reason for adding browser tests across the board :)

I meant dependencies as well, which should also be a problem right?

**Comment by vweevers** [comment]
Could be, most likely in devDependencies. We'll find out soon enough.
