### ISSUE TITLE
Check likely false positive vulnerabilities in devDependencies

### ISSUE THREAD

**Issue by jzombie** [Level/abstract-leveldown#384]
Noticed some high / critical vulnerabilities in the airtap package you're using.

![2021-11-01_11-12](https://user-images.githubusercontent.com/1139657/139711842-abee5caf-cc40-43bc-b92c-88ae1582547d.png)

**Comment by vweevers** [comment]
Renamed to not scare everyone.

**Comment by vweevers** [comment]
The vulnerability in `hallmark` is fixed by https://github.com/Level/abstract-leveldown/commit/6ab33b28df00dcaaa63ac16b80ef49465b81f17b.

The vulnerabilities in airtap are already tracked in https://github.com/airtap/airtap/issues/312 (and stuck on https://github.com/airtap/airtap/pull/317#issuecomment-946978873).
