### ISSUE TITLE
AbstractChainedBatch tests should commit and inspect db rather than sniff `_operations` buffer

### ISSUE THREAD

**Issue by deanlandolt** [Level/abstract-leveldown#87]
Nothing about `AbstractChainedBatch` requires it to keep operations around in memory (in the `_operations` buffer), but some of its tests sniff this buffer rather than committing these values and reading from the db. The tests are mostly around just verifying the _serialize[Key|Value] behavior, so in this case they would probably be better off hooking `_put` and `_del`. I do have to do all [this nonsense here](https://github.com/ralphtheninja/pgdown/blob/master/test/abstract-leveldown.js#L15-L43)) from outside the tests, but from within we could just hook the `_put` and `_del` methods on the batch directly.

Regardless, these tests should also commit these values and verify what ends up in the db w/ `collectEntries`. The only exception might be `test custom _serialize*`, since what will happen when this hits the db is undefined behavior. But this just suggests to me we should add companion `_deserialize[Key|Value]` methods to get us a hook to reliably verify expected results.

/cc @ralphtheninja @juliangruber

**Comment by vweevers** [comment]
Fixed by #88, except for:

> Regardless, these tests should also commit these values and verify what ends up in the db w/ collectEntries. The only exception might be test custom _serialize*, since what will happen when this hits the db is undefined behavior.

I think what we have is good. Serializing and committing is tested separately, as unit tests should. In addition, after #277, the default serialize functions will be identity functions. The idea behind that is we shouldn't make any assumptions about serialization - including in tests. So indeed, "what will happen when this hits the db is undefined behavior".
